#!/usr/bin/env php
<?php

ini_set('display_errors', 1);
error_reporting(-1);

$env = "dev";
$app = require __DIR__.'/src/SilexMarkdown/app.php';

$console = require __DIR__.'/src/SilexMarkdown/console.php';
$console->run();
